### PR TITLE
Fixed mixins to work with Forge more properly

### PR DESCRIPTION
**Pull request by SrRapero720**
Current version have next issues
- Mixins failed to be applied ``([14:06:07] [Server thread/FATAL] [mixin/]: Mixin apply failed vmp.mixins.json:chunk.sending.MixinThreadedAnvilChunkStorage -> net.minecraft.server.level.ChunkMap: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException PRIVATE @Overwrite method m_214908_ in vmp.mixins.json:chunk.sending.MixinThreadedAnvilChunkStorage cannot reduce visibiliy of PUBLIC target method)``
- Jar filename is "fabric" but is forge.

TESTED? YES!
I was making a modpack and current version causes a crash, i put mod with mixin fix and works fine with 220 mods!
image

### CODE REVIEW

**Comment by SrRapero720** [comment]
i also added few fixes + changes from upstream

**Review by ishland — CHANGES_REQUESTED** [review]
There are a few issues:
- These `vmp$` prefixes should be submitted upstream as adding them here makes updating upstream more time-consuming.
- Merge or rebase on upstream rather than cherry-picking upstream commits.

**Comment by SrRapero720** [comment]
- i can remove prefixes, i added it to prevent weird mixin stuff. 👍
- I dont understand what you mean... technically you can't merge or rebase from other repositories. and this repo is not a fork.

**Comment by ishland** [comment]
> I dont understand what you mean... technically you can't merge or rebase from other repositories. and this repo is not a fork.

This repository is a duplicate of the upstream repository. They have the same history and you can use command line to merge upstream.

**Pull request closed without merging**
